apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: centos
  name: centos
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      run: centos
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: centos
    spec:
      containers:
      - args:
        - bash
        image: centos
        imagePullPolicy: Always
        name: centos
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
