apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  template:
    metadata:
      name: helloworld
    spec:
      containers:
      - name: app
        image: python
        volumeMounts:
          - name: pythoncode
            mountPath: /application
        command: ["sh","-c"]
        args: ["cp /application/hello_world.py /tmp/; chmod +x /tmp/hello_world.py; /tmp/hello_world.py"]
      restartPolicy: Never
      volumes:
      - name: pythoncode
        configMap:
          name: test1234
          items:
            - key: hello_world.py
              path: hello_world.py
     
